#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'final-race-pkg','console_scripts','pure_pursuit_node'
__requires__ = 'final-race-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('final-race-pkg', 'console_scripts', 'pure_pursuit_node')()
    )
